name: Runs on Linux (Ubuntu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache raylib
      id: cache-raylib
      uses: actions/cache@v3
      with:
        path: /usr/local/lib/libraylib.so
        key: ${{ runner.os }}-raylib-${{ hashFiles('**/raylib/src/**') }}

    - name: Install raylib dependencies
      if: steps.cache-raylib.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Install raylib
      if: steps.cache-raylib.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/raysan5/raylib.git
        cd raylib/src
        make PLATFORM=PLATFORM_DESKTOP
        sudo make install

    - name: Build the project
      run: make linux

