name: Runs on Linux (Ubuntu)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache raylib
      id: cache-raylib
      uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/raylib-cache
        key: ${{ runner.os }}-raylib-${{ hashFiles('**/raylib/src/**') }}

    - name: Copy raylib files if cache hit
      if: steps.cache-raylib.outputs.cache-hit == 'true'
      run: |
        sudo mkdir -p /usr/local/lib /usr/local/include
        sudo cp ${{ github.workspace }}/raylib-cache/lib/* /usr/local/lib/
        sudo cp ${{ github.workspace }}/raylib-cache/include/* /usr/local/include/

    - name: Install raylib dependencies
      if: steps.cache-raylib.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev

    - name: Install raylib
      if: steps.cache-raylib.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/raysan5/raylib.git
        cd raylib/src
        make PLATFORM=PLATFORM_DESKTOP
        make install RAYLIB_INSTALL_PATH="${{ github.workspace }}/raylib-cache"
        sudo make install

    - name: Verify raylib installation
      run: |
        ls -l /usr/local/lib/libraylib*
        ls -l /usr/local/include/raylib.h

    - name: Build the project
      run: make linux

